### ISSUE TITLE
VAC DETECTED

### ISSUE THREAD

**Issue by hadengra** [Blaumaus/le_chiffre#11]
Hello, this cheat is likely detected from vac for a few reason. It's using many instances of things like WriteProcessMemory, or ReadProcessMemory. Which is obviously going to be detected by vac. I would recommend for anyone using this use Vac bypass. Now i haven't looked much into code specifically but glow can be easily detected by checking directx renderers, and i saw that you had glow.

**Comment by Blaumaus** [comment]
I wouldn't say it uses that many memory reads or writes as it might be.

But yes, playing with cheats as always a risk, which you are automatically accept when running it.

Also the cheat hs not been VAC detected yet.
Many people tested it and there wasn't a single report of VAC ban.

The problem is that the more popular cheat gets, the higher risk of VAC detection is.
That is the main factor of VAC detection (that's why private cheats are not get detected, no matter how crappy they are).

So if you want to minimise the risk of VAC ban - you should manipulate the code as much as possible to make it more unique.

**Comment by daniel11609** [comment]
Hey Blaumaus,

how exactly should I try getting it more unique? Any specific tipps what works / what not? 
Does Junk Code do anything ?

**Comment by Blaumaus** [comment]
@daniel11609, yes, adding some junk code might help in some cases, but the best you could do is to reimplement all the hacks you are using in some other way, rewrite the menu. 
Anyway, you should always at least rename the cheat file and change it's hash sum.
