### ISSUE TITLE
ALT+TAB = reset all settings to off

### ISSUE THREAD

**Issue by razeNFR** [Blaumaus/le_chiffre#63]
Hello,

i dont know why and its like that since the first release of the cheat, but, when i alt+tab the game, the cheat reset all settings to off, why and how i can fix that ? 

I have the source and i know how to compile the hack, so if someone know how to fix this problem, i will thank him :)

Cordially.

**Comment by Blaumaus** [comment]
@razeNFR there was such bug happening in the early releases of this software. I tried to fix it and it worked well (at least for me) on Windows 10 and 11.
This bug was possible to reproduce by pressing 'Win' button, but for me it's working fine now..
I don't know what's causing this issue, it would be great if you could dig into it and give me some directions on how to fix it, or maybe open a PR yourself, it would be great.

**Comment by razeNFR** [comment]
How you fixed it ? 

And sorry but im very noob in progammation so i cant very help you..Also I tried to perfect the bunnyhop, but I couldn't find the solution either :(

**Comment by Liuhaixv** [comment]
fixed and waiting for merging

> @razeNFR there was such bug happening in the early releases of this software. I tried to fix it and it worked well (at least for me) on Windows 10 and 11. This bug was possible to reproduce by pressing 'Win' button, but for me it's working fine now.. I don't know what's causing this issue, it would be great if you could dig into it and give me some directions on how to fix it, or maybe open a PR yourself, it would be great.

**Comment by Liuhaixv** [comment]
I have suffered from this glitch every time when switching between game and desktop using ALT + TAB

**Comment by Blaumaus** [comment]
@Liuhaixv thanks for the fix. I'll review and merge it later today.

**Comment by Liuhaixv** [comment]
ok

**Comment by Blaumaus** [comment]
@Liuhaixv sorry it took long to merge, thanks for your PR.
@razeNFR the issue if fixed in the [v1.5.0](https://github.com/Blaumaus/le_chiffre/releases/tag/v1.5.0) release.
